index:
    path: /
    controller: App\Pages\Login::index

dashboard:
    path: /dashboard/
    controller: App\Pages\Dashboard::index

logout:
    path: /logout/
    controller: App\Controller\PageController::logout

uploadNotes:
    path: /notes/upload/
    controller: App\Pages\Upload:notes

uploadTimetables:
    path: /timetables/upload/
    controller: App\Pages\Upload:timetables
