index:
    path: /
    controller: App\Pages\Login::index

dashboard:
    path: /dashboard/
    controller: App\Pages\Dashboard::index

logout:
    path: /logout/
    controller: App\Controller\PageController::logout

uploadNotes:
    path: /notes/upload/
    controller: App\Pages\Upload:notes

uploadTimetables:
    path: /timetables/upload/
    controller: App\Pages\Upload:timetables

timetables:
    path: /downloads/timetables/
    controller: App\Pages\Downloads:timetables

apiTimetables:
    path: /api/timetables/
    controller: App\Controller\ApiController:timetables

notes:
    path: /downloads/notes/
    controller: App\Pages\Downloads:notes

apiNotes:
    path: /api/notes/
    controller: App\Controller\ApiController:notes

announcements:
    path: /announcements/
    controller: App\Pages\Announcements:index

viewAnnouncement:
    path: /announcements/view/{id}/
    controller: App\Pages\Announcements:view

newAnnouncement:
    path: /announcements/new/
    controller: App\Pages\Announcements:new

editAnnouncement:
    path: /announcements/edit/{id}/
    controller: App\Pages\Announcements:edit

deleteAnnouncement:
    path: /announcements/delete/{id}/
    controller: App\Pages\Announcements:delete

apiAnnouncements:
    path: /api/announcements/
    controller: App\Controller\ApiController:announcements
