index:
    path: /
    controller: App\Pages\Login::index

dashboard:
    path: /dashboard/
    controller: App\Controller\DefaultController::dashboard

logout:
    path: /logout/
    controller: App\Controller\DefaultController::logout

uploadNotes:
    path: /uploads/notes/
    controller: App\Pages\Uploads:notes

uploadTimetables:
    path: /uploads/timetables/
    controller: App\Pages\Uploads:timetables

timetables:
    path: /downloads/timetables/
    controller: App\Pages\Downloads:timetables

apiTimetables:
    path: /api/timetables/
    controller: App\Controller\ApiController:timetables

notes:
    path: /downloads/notes/
    controller: App\Pages\Downloads:notes

apiNotes:
    path: /api/notes/
    controller: App\Controller\ApiController:notes

announcements:
    path: /announcements/
    controller: App\Controller\AnnouncementsController::index

viewAnnouncement:
    path: /announcements/view/{id}/
    controller: App\Controller\AnnouncementsController::view

newAnnouncement:
    path: /announcements/new/
    controller: App\Controller\AnnouncementsController::new

editAnnouncement:
    path: /announcements/edit/{id}/
    controller: App\Controller\AnnouncementsController::edit

deleteAnnouncement:
    path: /announcements/delete/{id}/
    controller: App\Controller\AnnouncementsController::delete

apiAnnouncements:
    path: /api/announcements/
    controller: App\Controller\ApiController:announcements

complaints:
    path: /complaints/
    controller: App\Controller\ComplaintsController::index

newComplaint:
    path: /complaints/new/
    controller: App\Controller\ComplaintsController::new

viewComplaint:
    path: /complaints/view/{id}/
    controller: App\Controller\ComplaintsController::view

deleteComplaint:
    path: /complaints/delete/{id}/
    controller: App\Controller\ComplaintsController::delete

apiComplaints:
    path: /api/complaints/
    controller: App\Controller\ApiController:complaints

courses:
    path: /courses/
    controller: App\Pages\Courses:index

newCourse:
    path: /courses/new/
    controller: App\Pages\Courses:new

viewCourse:
    path: /courses/view/{id}/
    controller: App\Pages\Courses:view

editCourse:
    path: /courses/edit/{id}/
    controller: App\Pages\Courses:edit

deleteCourse:
    path: /courses/delete/{id}/
    controller: App\Pages\Courses:delete

apiCourses:
    path: /api/courses/
    controller: App\Controller\ApiController:courses

users:
    path: /users/
    controller: App\Pages\Users:index

newUser:
    path: /users/new/
    controller: App\Pages\Users:new

apiUsers:
    path: /api/users/
    controller: App\Controller\ApiController:users

updateUser:
    path: /users/profile/{id}/
    controller: App\Pages\Users:profile
