index:
    path: /
    controller: App\Pages\Login::index

dashboard:
    path: /dashboard/
    controller: App\Pages\Dashboard::index

logout:
    path: /logout/
    controller: App\Controller\PageController::logout
